# This is a basic workflow to help you get started with Actions

name: BrainDeadStudios CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths-ignore: 
      - 'Docs/**'
      - 'Wiki/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@master
      
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0
      with:
        vs-version: "[16.4,16.6]"
        
    - name: Checking msbuild path
      run: echo "${{ steps.setup_msbuild.outputs.msbuildPath }}"

    - name: Checking MSBuild version
      run: msbuild -version
    
    - name: Building the project with release configuration
      run: MSBuild Game_Solution.sln /property:Configuration=Debug

      
